f = linspace(0, 10, 1000);
w = 2*pi*f;
as = 4 * (sin(w./2).^2);
as = sqrt(abs(as));
as = as + eps;
logas = 10*log10(as);
figure('Name','Delay Line Canceller Amplitude Response');
plot(f,as);
title('Single Delay Canceler');
xlabel('normalized frequency');
ylabel('amplitude response');
figure('Name', 'Delay Line Canceller Amplitude Response in dB');
plot(f,logas);
axis('tight');
title('Single Delay Canceler');
xlabel('normalized frequency');
ylabel('amplitude response in dB');
